// @ts-check

export const ENTITY_COLLECTIONS = Object.freeze({
  User: 'users',
  Company: 'companies',
  CompanyMember: 'companyMembers',
  CompanyMetric: 'companyMetrics',
  CompanyMonthlyMetric: 'companyMonthlyMetrics',
  Document: 'documents',
  Transaction: 'transactions',
  AuditLog: 'auditLogs',
  CRMClient: 'crmClients',
  CRMDeal: 'crmDeals',
  CRMInteraction: 'crmInteractions',
  Employee: 'employees',
  Payroll: 'payroll',
  PerformanceReview: 'performanceReviews',
  KPI: 'kpis',
  Subscription: 'subscriptions',
  PredictionLog: 'predictionLogs',
  AIConversation: 'aiConversations',
  Project: 'projects',
  ProjectTask: 'projectTasks',
  SupportTicket: 'supportTickets',
  ObservabilityEvent: 'observabilityEvents',
  ImportLog: 'importLogs',
});
