#!/usr/bin/env bash
# Configuración compartida por la compilación y las pruebas E2E.
export VITE_FIREBASE_API_KEY=demo-api-key
export VITE_FIREBASE_AUTH_DOMAIN=demo-gemailla-e2e.firebaseapp.com
export VITE_FIREBASE_PROJECT_ID=demo-gemailla-e2e
export VITE_FIREBASE_STORAGE_BUCKET=demo-gemailla-e2e.appspot.com
export VITE_FIREBASE_MESSAGING_SENDER_ID=000000000000
export VITE_FIREBASE_APP_ID=1:000000000000:web:demo
export CLOUDSDK_CONFIG=/tmp/gemailla-emulator-cloudsdk
export GCLOUD_PROJECT="$VITE_FIREBASE_PROJECT_ID"
export GOOGLE_CLOUD_PROJECT="$VITE_FIREBASE_PROJECT_ID"
export VERTEX_GEMINI_PROJECT="$VITE_FIREBASE_PROJECT_ID"
export FIRESTORE_EMULATOR_HOST=127.0.0.1:8080
export FIREBASE_AUTH_EMULATOR_HOST=127.0.0.1:9099
export FIREBASE_STORAGE_EMULATOR_HOST=127.0.0.1:9199
export STORAGE_EMULATOR_HOST="http://$FIREBASE_STORAGE_EMULATOR_HOST"

export FUNCTIONS_DISCOVERY_TIMEOUT=60
