const assert = require('node:assert/strict'); const test = require('node:test'); const firebaseAdmin = require('../firebaseAdmin'); const { predictionLogHandler } = require('../handlers/predictionLogHandler');
const req = (body, tokens = true) => ({ method: 'POST', body, get: name => !tokens ? '' : name.toLowerCase() === 'x-firebase-appcheck' ? 'app' : name.toLowerCase() === 'authorization' ? 'Bearer auth' : '' }); const res = () => ({ statusCode: 0, status(code) { this.statusCode = code; return this; }, json(body) { this.body = body; return this; } });
function mock(t, { count = 0, member = true, entitlement } = {}) { const writes = new Map(); let queryReads = 0; const activeEntitlement = entitlement === undefined ? validEntitlement('pro') : entitlement; const originals = [firebaseAdmin.getAdminAppCheck, firebaseAdmin.getAdminAuth, firebaseAdmin.getAdminFirestore]; firebaseAdmin.getAdminAppCheck = () => ({ verifyToken: async token => { if (token !== 'app') throw new Error('bad'); } }); firebaseAdmin.getAdminAuth = () => ({ verifyIdToken: async () => ({ uid: 'u1', email: 'u@test.invalid' }) }); const predictionCollection = { doc: id => ({ kind: 'doc', id }), where() { return this; } }; const db = { collection(name) { if (name === 'companyMembers') return { doc: () => ({ get: async () => ({ exists: member, data: () => ({ companyId: 'acme', userUid: 'u1', status: 'active' }) }) }) }; if (name === 'companyEntitlements') return { doc: id => ({ get: async () => ({ exists: Boolean(activeEntitlement), id, data: () => activeEntitlement }) }) }; return predictionCollection; }, runTransaction: async callback => callback({ get: async target => { if (target.kind === 'doc') return { exists: writes.has(target.id) }; queryReads += 1; return { size: count }; }, create: (ref, payload) => writes.set(ref.id, payload) }) }; firebaseAdmin.getAdminFirestore = () => db; writes.queryReads = () => queryReads; t.after(() => { [firebaseAdmin.getAdminAppCheck, firebaseAdmin.getAdminAuth, firebaseAdmin.getAdminFirestore] = originals; }); return writes; }
function validEntitlement(plan, overrides = {}) { return { companyId: 'acme', plan, status: 'active', aiAccess: plan !== 'basic', currentPeriodEnd: '2999-01-01T00:00:00.000Z', ...overrides }; }
async function invoke(body) { const response = res(); await predictionLogHandler(req(body), response); return response; }
test('exige correlationId único y diferencia 401/403', async t => { mock(t, { member: false }); const missing = await invoke({ companyId: 'acme', correlationId: '' }); assert.equal(missing.statusCode, 400); const unauth = res(); await predictionLogHandler(req({}, false), unauth); assert.equal(unauth.statusCode, 401); const forbidden = await invoke({ companyId: 'acme', correlationId: 'corr-0001' }); assert.equal(forbidden.statusCode, 403); });
test('duplicado es idempotente y dos correlaciones crean predicciones distintas', async t => { const writes = mock(t); const one = { companyId: 'acme', correlationId: 'corr-0001', type: 'cashflow' }; assert.equal((await invoke(one)).statusCode, 201); const duplicate = await invoke(one); assert.equal(duplicate.statusCode, 200); assert.equal(duplicate.body.duplicate, true); assert.equal((await invoke({ ...one, correlationId: 'corr-0002' })).statusCode, 201); assert.equal(writes.size, 2); });
test('Basic activo con aiAccess=false registra por debajo de 5', async t => { const writes = mock(t, { count: 4, entitlement: validEntitlement('basic') }); const response = await invoke({ companyId: 'acme', correlationId: 'corr-basic-ok' }); assert.equal(response.statusCode, 201); assert.equal(writes.values().next().value.planAtCreation, 'basic'); });
test('Basic activo aplica el límite de 5', async t => { mock(t, { count: 5, entitlement: validEntitlement('basic') }); assert.equal((await invoke({ companyId: 'acme', correlationId: 'corr-basic-limit' })).statusCode, 403); });
test('Pro activo registra por debajo de 50', async t => { mock(t, { count: 49, entitlement: validEntitlement('pro') }); assert.equal((await invoke({ companyId: 'acme', correlationId: 'corr-pro-ok' })).statusCode, 201); });
test('Pro activo aplica el límite de 50', async t => { mock(t, { count: 50, entitlement: validEntitlement('pro') }); assert.equal((await invoke({ companyId: 'acme', correlationId: 'corr-pro-limit' })).statusCode, 403); });
test('Enterprise registra sin lectura mensual innecesaria', async t => { const writes = mock(t, { entitlement: validEntitlement('enterprise'), count: 999 }); const response = await invoke({ companyId: 'acme', correlationId: 'corr-enterprise' }); assert.equal(response.statusCode, 201); assert.equal(writes.queryReads(), 0); });
test('entitlement ausente conserva el fallback Basic y su límite', async t => { mock(t, { count: 4, entitlement: null }); assert.equal((await invoke({ companyId: 'acme', correlationId: 'corr-missing-ok' })).statusCode, 201); });
test('entitlement ausente no supera el límite Basic', async t => { mock(t, { count: 5, entitlement: null }); assert.equal((await invoke({ companyId: 'acme', correlationId: 'corr-missing-limit' })).statusCode, 403); });

for (const [index, [name, entitlement]] of [
  ['expirado', validEntitlement('pro', { currentPeriodEnd: '2000-01-01T00:00:00.000Z' })],
  ['de otra empresa', validEntitlement('pro', { companyId: 'other' })],
  ['con status inválido', validEntitlement('pro', { status: 'cancelled' })],
  ['con plan desconocido', validEntitlement('unknown', { aiAccess: true })],
].entries()) {
  test(`recordPrediction rechaza entitlement ${name}`, async t => { mock(t, { entitlement }); assert.equal((await invoke({ companyId: 'acme', correlationId: `corr-denied-${index}` })).statusCode, 403); });
}
