const assert = require('node:assert/strict'); const test = require('node:test');
const { createHash } = require('node:crypto'); const { Timestamp } = require('firebase-admin/firestore');
const { EICAR, MAX_BYTES, quarantineScannerHandler, scanWithProvider, validateContent } = require('../handlers/quarantineScanner');
const event = (overrides = {}, id = 'event-1') => ({ id, data: { name: 'companies/acme/quarantine/doc/a.pdf', generation: '7', bucket: 'b', size: 10, contentType: 'application/pdf', metadata: { companyId: 'acme', documentId: 'doc' }, ...overrides } });
function harness(initial = { companyId: 'acme' }, options = {}) {
  let data = initial; const calls = { updates: [], copy: 0, delete: 0 };
  const ref = { update: async patch => { data = { ...data, ...patch }; calls.updates.push(patch); } };
  const snapshot = () => ({ exists: data !== null, data: () => data });
  let queue = Promise.resolve(); const firestore = { collection: () => ({ doc: () => ref }), runTransaction(callback) { const result = queue.then(() => callback({ get: async () => snapshot(), update: (_ref, patch) => { data = { ...data, ...patch }; calls.updates.push(patch); } })); queue = result.catch(() => {}); return result; } };
  const bytes = options.bytes || Buffer.from('%PDF-1.7'); let destinationExists = Boolean(options.destinationExists); const expectedHash = createHash('sha256').update(bytes).digest('hex');
  const destination = { exists: async () => [destinationExists], getMetadata: async () => [{ metadata: options.destinationMetadata || { sourceGeneration: '7', sha256: expectedHash, companyId: 'acme', documentId: 'doc' } }] };
  const source = { download: async () => [bytes], copy: async () => { calls.copy += 1; destinationExists = true; }, delete: async () => { calls.delete += 1; if (options.deleteFails) throw new Error('delete failed'); } };
  return { calls, data: () => data, dependencies: { firestore, bucket: { file: name => name.includes('/quarantine/') ? source : destination }, scan: options.scan || (async () => true) } };
}
test('rechaza EICAR, MIME falso, firma falsa y XML inseguro', () => { assert.throws(() => validateContent(Buffer.from(`%PDF-${EICAR}`), 'a.pdf', 'application/pdf'), /EICAR/); assert.throws(() => validateContent(Buffer.from('%PDF-'), 'a.xml', 'application/pdf'), /MIME/); assert.throws(() => validateContent(Buffer.from('fake'), 'a.pdf', 'application/pdf'), /Firma PDF/); assert.throws(() => validateContent(Buffer.from('<?xml?><!DOCTYPE x [<!ENTITY y SYSTEM "file:">]>'), 'a.xml', 'application/xml'), /XML inseguro/); });
test('tamaño o empresa inválidos no modifican documentos', async () => { const big = harness(); await quarantineScannerHandler(event({ size: MAX_BYTES }), big.dependencies); assert.equal(big.calls.updates.length, 0); const invalid = harness(null); await quarantineScannerHandler(event(), invalid.dependencies); assert.equal(invalid.calls.updates.length, 0); });
test('antivirus caído permite reintento y archivo infectado queda rechazado', async () => { const down = harness(undefined, { scan: async () => { throw new Error('caído'); } }); await quarantineScannerHandler(event(), down.dependencies); assert.equal(down.data().scanStatus, 'scan_error'); const rejected = harness(undefined, { scan: async () => false }); await quarantineScannerHandler(event(), rejected.dependencies); assert.equal(rejected.data().scanStatus, 'rejected'); });
test('handler completo clasifica EICAR como rejected', async () => { const h = harness(undefined, { bytes: Buffer.from(`%PDF-${EICAR}`) }); const result = await quarantineScannerHandler(event(), h.dependencies); assert.equal(result.promoted, false); assert.equal(h.data().scanStatus, 'rejected'); });
test('Promise.all del mismo evento solo escanea y copia una vez', async () => { let scans = 0; const h = harness(undefined, { scan: async () => { scans += 1; await new Promise(resolve => setTimeout(resolve, 10)); return true; } }); const [first, second] = await Promise.all([quarantineScannerHandler(event(), { ...h.dependencies, attemptId: 'a1' }), quarantineScannerHandler(event(), { ...h.dependencies, attemptId: 'a2' })]); assert.equal(scans, 1); assert.equal(h.calls.copy, 1); assert.ok(first.promoted || second.promoted); assert.ok(first.busy || second.busy); });
test('lease vencido permite un nuevo claim', async () => { const h = harness({ companyId: 'acme', scanStatus: 'processing', scanEventId: 'old', scanGeneration: '7', scanLeaseUntil: Timestamp.fromMillis(1) }); const result = await quarantineScannerHandler(event(), { ...h.dependencies, nowMs: 1000, attemptId: 'new' }); assert.equal(result.promoted, true); });
test('evento repetido limpio es idempotente', async () => { const h = harness({ companyId: 'acme', scanStatus: 'clean', storagePath: 'companies/acme/documents/doc/a.pdf' }); const result = await quarantineScannerHandler(event(), h.dependencies); assert.equal(result.repeated, true); assert.equal(h.calls.copy, 0); });
test('fallo al borrar no cambia clean a rejected', async () => { const h = harness(undefined, { deleteFails: true }); const result = await quarantineScannerHandler(event(), h.dependencies); assert.equal(result.promoted, true); assert.equal(h.data().scanStatus, 'clean'); assert.equal(h.data().quarantineCleanupPending, true); });
test('copia preexistente se reutiliza y finaliza clean', async () => { const h = harness(undefined, { destinationExists: true }); const result = await quarantineScannerHandler(event(), h.dependencies); assert.equal(result.promoted, true); assert.equal(h.calls.copy, 0); assert.equal(h.data().scanStatus, 'clean'); });
test('copia preexistente con hash o metadata distinta se bloquea', async () => { const h = harness(undefined, { destinationExists: true, destinationMetadata: { sourceGeneration: 'other', sha256: 'bad', companyId: 'acme', documentId: 'doc' } }); const result = await quarantineScannerHandler(event(), h.dependencies); assert.equal(result.promoted, false); assert.equal(h.data().scanStatus, 'scan_error'); });
test('proveedor antivirus falla cerrado', async () => { const old = process.env.MALWARE_SCANNER_URL; process.env.MALWARE_SCANNER_URL = 'https://scanner.test'; await assert.rejects(scanWithProvider(Buffer.from('x'), { contentType: 'application/pdf' }, async () => ({ ok: false, status: 503 })), /no disponible/); if (old === undefined) delete process.env.MALWARE_SCANNER_URL; else process.env.MALWARE_SCANNER_URL = old; });
